version: 2.1

orbs: 
    python: circleci/python@2.0.1
    
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest
            pip install request
            pytest --junitxml=test-results/junit.xml test_Github.py
      - store_test_results:
          path: test-results

workflows:
  GithubAPI:
    jobs:
      - build-and-test
